[tool.poetry]
name = "tblastn_wrapper"
version = "0.1.13"
description = "A wrapper for tblastn that parallelises queries"
authors = ["Yasir Kusay <yasir.kusay@student.unsw.edu.au>", "Cadel Watson <cadel@cadelwatson.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
mypy = "^0.782"

[tool.poetry.scripts]
tblastn_wrapper = "tblastn_wrapper.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
