[tool.black]
line-length=88
fast=true
target-version=["py36", "py37", "py38"]
[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
combine_as_imports=true
line_length=88
ensure_newline_before_comments=true
[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38, lint

[testenv]
commands =
    coverage run
    coverage report
deps =
    coverage[toml]

[testenv:lint]
commands =
    black . --check
    isort . --check-only
deps =
    black
    isort[pyproject]
"""
[tool.coverage.run]
branch=true
source=["easy_env_var"]
command_line="-m unittest"
[tool.coverage.report]
precision=3
fail_under=90.00
show_missing=true
