[tool.poetry]
name = "koroviev"
version = "0.1.2"
description = "CLI Util for project code gen by jinja snippets"
authors = ["Alexander Lavrov <internal@egnod.dev>"]
license = "MIT"

keywords = ["packaging", "dependency", "koroviev", "codegen", "code", "generator"]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

packages = [
    { include = "koroviev" },
]

[tool.poetry.scripts]
koroviev = "koroviev.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
fire = "^0.3.1"
pyyaml = "^5.3.1"
loguru = "^0.5.2"
termcolor = "^1.1.0"
pydantic = "^1.6.1"
jinja2 = "^2.11.2"

[tool.poetry.dev-dependencies]
bump2version = "^1.0.0"
pre-commit = "^2.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
