[tool.poetry]
name = "crdatamgt"
version = "3.0.32"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8.0"
pandas = "1.1.0"
simplelogging = "^0.10.0"
PyYaml = "^5.3.1"
openpyxl = "^3.0.4"
xlsxwriter = "^1.3.0"
toolz = "^0.10.0"
xloaderx = "^0.1.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
