[tool.poetry]
name = "tropic"
version = "0.2.5"
description = ""
authors = ["skip"]

[tool.poetry.dependencies]
python = "^3.8"
tensorflow = "^2.3.0"
logzero = "^1.5.0"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
wemake-python-styleguide = "^0.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
