[build-system]
requires = [
    "setuptools >= 49",
    "setuptools_scm[toml] >= 4",
    "wheel >= 0.35",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "src/jomiel/__init__.py"
write_to_template = "__version__ = {version!r}"

[tool.black]
target-version = ['py38']
line-length = 72
exclude = '''
(
    /(
        \.eggs
        \.git
        \.tox
        build
        dist
    )/
)
'''
